from enum import Enum

class ActionType(str, Enum):
    REMINDER = "REMINDER"
    PAYMENT_LINK = "PAYMENT_LINK"
    PROMISE_TO_PAY = "PROMISE_TO_PAY"
    ESCALATE = "ESCALATE"
    STOP = "STOP"

class CaseState(str, Enum):
    PAYMENT_FAILED = "PAYMENT_FAILED"
    RECOVERY_ELIGIBLE = "RECOVERY_ELIGIBLE"
    ACTION_EVALUATION = "ACTION_EVALUATION"
    ACTION_RESERVED = "ACTION_RESERVED"
    ACTION_EXECUTING = "ACTION_EXECUTING"
    ACTION_CONFIRMED = "ACTION_CONFIRMED"
    WAITING_FOR_OUTCOME = "WAITING_FOR_OUTCOME"
    OUTCOME_RECONCILIATION = "OUTCOME_RECONCILIATION"
    RE_EVALUATE = "RE_EVALUATE"
    RECOVERED = "RECOVERED"
    STOPPED = "STOPPED"
    EXECUTION_UNKNOWN = "EXECUTION_UNKNOWN"
    MANUAL_REVIEW_REQUIRED = "MANUAL_REVIEW_REQUIRED"
    UNRECOVERABLE = "UNRECOVERABLE"

class PromiseState(str, Enum):
    PROMISE_PROPOSED = "PROMISE_PROPOSED"
    PROMISE_ACCEPTED = "PROMISE_ACCEPTED"
    PROMISE_DUE = "PROMISE_DUE"
    PROMISE_FULFILLED = "PROMISE_FULFILLED"
    PROMISE_MISSED = "PROMISE_MISSED"
    PROMISE_EXPIRED = "PROMISE_EXPIRED"

class ExecutionStatus(str, Enum):
    PENDING = "PENDING"
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"
    UNKNOWN = "UNKNOWN"
    TIMEOUT = "TIMEOUT"

class RecoveryStatus(str, Enum):
    UNRECOVERED = "UNRECOVERED"
    PARTIALLY_RECOVERED = "PARTIALLY_RECOVERED"
    FULLY_RECOVERED = "FULLY_RECOVERED"

class PaymentStatus(str, Enum):
    CREATED = "CREATED"
    FAILED = "FAILED"
    AUTHORIZED = "AUTHORIZED"
    CAPTURED = "CAPTURED"
    REFUNDED = "REFUNDED"

class FailureCode(str, Enum):
    INSUFFICIENT_FUNDS = "INSUFFICIENT_FUNDS"
    AUTHENTICATION_FAILED = "AUTHENTICATION_FAILED"
    GATEWAY_DOWNTIME = "GATEWAY_DOWNTIME"
    CARD_EXPIRED = "CARD_EXPIRED"
    NETWORK_TIMEOUT = "NETWORK_TIMEOUT"
    USER_DROPPED = "USER_DROPPED"

class CustomerSegment(str, Enum):
    STANDARD = "STANDARD"
    VIP = "VIP"
    NEW = "NEW"
    AT_RISK = "AT_RISK"

class ChannelPreference(str, Enum):
    SMS = "SMS"
    WHATSAPP = "WHATSAPP"
    EMAIL = "EMAIL"

class EvaluationArm(str, Enum):
    ARM_A_CONTROL = "CONTROL"
    ARM_B_BASELINE = "DETERMINISTIC_BASELINE"
    ARM_C_RECOVERIQ = "RECOVERIQ"
